/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.solfadministration.model.GUI;

import ec.espe.edu.solfadministration.Files.util.FileManager;
import ec.espe.edu.solfadministration.Files.util.Validations;
import ec.espe.edu.solfadministrationprj.model.Inventory;
import ec.espe.edu.solfadministrationprj.model.Product;
import ec.espe.edu.solfadministrationprj.model.Store;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Loachamin
 */
public class BillingJFrame extends javax.swing.JFrame implements ItemListener{
  Scanner input = new Scanner(System.in);
	Store shop = new Store();
	private Inventory product;
	private int codeSaleProduct;
	private float quantityProductSold;
	private float iva;
	private float total;
	private int multiplicity;
	private String nameProduct;
	private float subtotal;
        private JTextField tf;

    public float getSubtotal() {
        return subtotal;
    }
	private float totalSold;

    public float getTotalSold() {
		return totalSold;
    }

    public float getIva() {
        return iva;
    }

ArrayList<Product> bill = new ArrayList<Product>();
DefaultTableModel  model = new DefaultTableModel();

    /**
     * Creates new form NewJFrame
     */
    public BillingJFrame() {
        this.setTitle("Facturación");
        initComponents();
        model.addColumn("CANTIDAD");
        model.addColumn("PRODUCTO");
        model.addColumn("PRECIO");
        model.addColumn("TOTAL");
        tableProduct.setModel(model);
      
     ArrayList<Product> products1 = new ArrayList<Product>();
    File file =new File("Product.txt");
     FileManager.createArrayOfFile(products1,file);
	for (int i = 0; i < products1.size(); i++) {
	           this.cmbxNameProduct.addItem(products1.get(i).getNameProduct());                    
        }
        FileManager.saveArrayInFile(file, products1);
         products1.clear(); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLblProduct = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQuantly = new javax.swing.JTextField();
        btnAgregation = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        radiobtnConsumerEnd = new javax.swing.JRadioButton();
        radiobtnInformation = new javax.swing.JRadioButton();
        btnGenerateBilling = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        cmbxNameProduct = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblNameUser = new javax.swing.JLabel();
        lblCi = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblLocate = new javax.swing.JLabel();
        txtNameProduct = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtLocate = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(102, 204, 0));

        jLblProduct.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLblProduct.setText("Ingrese el Nombre del Producto");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese la Cantidad del Producto");

        txtQuantly.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantlyKeyTyped(evt);
            }
        });

        btnAgregation.setBackground(new java.awt.Color(0, 0, 153));
        btnAgregation.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregation.setText("Agregar\n");
        btnAgregation.setPreferredSize(new java.awt.Dimension(80, 25));
        btnAgregation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregationActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.setMaximumSize(new java.awt.Dimension(80, 25));
        btnClear.setMinimumSize(new java.awt.Dimension(80, 25));
        btnClear.setPreferredSize(new java.awt.Dimension(80, 25));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calcular");
        btnCalculate.setPreferredSize(new java.awt.Dimension(80, 25));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        Group1.add(radiobtnConsumerEnd);
        radiobtnConsumerEnd.setText("Consumidor Final");

        Group1.add(radiobtnInformation);
        radiobtnInformation.setText("Información");
        radiobtnInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnInformationMouseClicked(evt);
            }
        });
        radiobtnInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnInformationActionPerformed(evt);
            }
        });

        btnGenerateBilling.setText("Generar Factura");
        btnGenerateBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillingActionPerformed(evt);
            }
        });

        tableProduct.setBackground(new java.awt.Color(223, 176, 176));
        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CANTIDAD", "PRODUCTO", " PRECIO", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProduct);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 0, 0));
        jLabel1.setText("SISTEMA DE FACTURACIÓN");

        jLabel3.setText("Subtotal:");

        jLabel4.setText("IVA 12%: ");

        jLabel5.setText("Total  Pagar: ");

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cmbxNameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxNameProductActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNameUser.setText("Nombre y Apellido:");

        lblCi.setText("CI:");

        lblNumber.setText("Telefono");

        lblLocate.setText("Ciudad:");

        txtCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCIKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocate, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 192, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbxNameProduct, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantly, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(btnDelete)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerateBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(radiobtnConsumerEnd)
                                .addGap(122, 122, 122)
                                .addComponent(radiobtnInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnAgregation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantly, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete))
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGenerateBilling)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiobtnConsumerEnd)
                            .addComponent(radiobtnInformation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        jLblProduct.getAccessibleContext().setAccessibleName("jLbl\n");

        jMenu1.setText("Menú");

        jMenuItem1.setText("Ver Productos ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Volver");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administración");

        jMenuItem3.setText("Acerca de");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("JLbl1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
    generateBilling();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnGenerateBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillingActionPerformed
        if(radiobtnInformation.isSelected()){
        generateBill(new File("Factura.txt"));
        JOptionPane.showMessageDialog(null,"FACTURA GENERADA");
        }if(radiobtnConsumerEnd.isSelected()){
            generateBillConsumerEnd(new File("Factura.txt"));
            JOptionPane.showMessageDialog(null,"FACTURA GENERADA");
               
        }
           
    }//GEN-LAST:event_btnGenerateBillingActionPerformed

    private void radiobtnInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnInformationActionPerformed

    private void btnAgregationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregationActionPerformed
         
         
        try{
              
                actionPerformedTable(evt);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Eliga un producto");     
       }
       
    }//GEN-LAST:event_btnAgregationActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearTextField();
        clearTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteProduct(evt);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cmbxNameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxNameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxNameProductActionPerformed

    private void txtQuantlyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantlyKeyTyped
      char validate=evt.getKeyChar();
      boolean valido = false;
      if(Character.isLetter(validate)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog(null,"ingrese solo numero");
      }
    else if (validate == '-') {
    Object component = evt.getComponent();
    if (component instanceof JTextField) {
        JTextField tf = (JTextField)component;
        valido = tf.getText().isEmpty(); 
    }
    if (valido==true) {
    evt.consume();
    JOptionPane.showMessageDialog(null,"ingrese solo numero positivos");
   }
      
   
    }        
    }//GEN-LAST:event_txtQuantlyKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmInventoryStatus frmEmployeeInventory = new FrmInventoryStatus();
     frmEmployeeInventory.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      FrmEmployeeMenu frmEmployeeMenu = new FrmEmployeeMenu();
     frmEmployeeMenu.setLocationRelativeTo(null);
      frmEmployeeMenu.setVisible(true);
        dispose();
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void radiobtnInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnInformationMouseClicked
        


    }//GEN-LAST:event_radiobtnInformationMouseClicked

    private void txtCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIKeyTyped


                       
    }//GEN-LAST:event_txtCIKeyTyped

 protected void actionPerformedTable(ActionEvent e){
    model.setRowCount(0);
    float total;
    int multiplicity =0;
    boolean existence = false;
    DecimalFormatSymbols symbolFormat = new DecimalFormatSymbols();
    symbolFormat.setDecimalSeparator('.');
    DecimalFormat decimalFormat = new DecimalFormat("#.00", symbolFormat);
 
     String nameProduct=cmbxNameProduct.getSelectedItem().toString();
    multiplicity =Integer.parseInt(txtQuantly.getText());
   
    File file =new File("Product.txt");
    ArrayList<Product> products = new ArrayList<Product>();
       
        FileManager.createArrayOfFile(products,file);
	for (int i = 0; i < products.size(); i++) {
	   if (products.get(i).getNameProduct().equals(nameProduct)) {
               if (products.get(i).getStock() <= 0) {
		
		 products.get(i).setStock(0);
                 FileManager.saveArrayInFile(file, products);
                products.clear();
                   
                 JOptionPane.showMessageDialog(null,"PRODUCTO NO DISPONIBLE");
		 existence = true;

		} else {
               
		total = (float) (products.get(i).getCost() * multiplicity);
                String y;
                y=String.valueOf(multiplicity);
                 int totalStock = products.get(i).getStock() - multiplicity;
		 products.get(i).setStock(totalStock);
                bill.add(new Product(products.get(i).getNameProduct(),y,total,products.get(i).getCost())); 
                FileManager.saveArrayInFile(file, products);
                products.clear(); 
                existence = true;     
           }
           }          
        }
        if (existence == false) {
		JOptionPane.showMessageDialog(null,"PRODUCTO NO EXISTE");
                
       }else {
       subtotal=0;	
       
      for(int i=0;i<bill.size();i++){
          subtotal = subtotal + bill.get(i).getTotal();
          totalSold = subtotal * 1.12f;
          iva = totalSold - subtotal;
         totalSold = Float.parseFloat(decimalFormat.format(totalSold));
                 
          Object[] fila ={
              bill.get(i).getCodeProduct(),bill.get(i).getNameProduct(),bill.get(i).getCost(),bill.get(i).getTotal()
          };
        model.addRow(fila);
      }
     
    txtQuantly.setText("");
   
    
            
                                        
}
 } public void clearTextField(){  
     
      txtQuantly.setText("");
  }
  public void generateBilling(){

       jLabel3.setText("Subtotal:"+getSubtotal());
       jLabel4.setText("IVA 12%: "+getIva());
       jLabel5.setText("Total  Pagar: "+getTotalSold());
  }
   public void clearTable(){
      
 int a =tableProduct.getRowCount()-1;

for(int i=a; i>=0; i--){
model.removeRow(model.getRowCount()-1);
}
      jLabel3.setText("Subtotal:");
       jLabel4.setText("IVA 12%: ");
       jLabel5.setText("Total  Pagar: ");
      
  }
   protected void deleteProduct(ActionEvent e){
       int btn;
       int resp = 0;
       int fila;
       try{
           btn =tableProduct.getSelectedRow();
           if(btn==-1){
               JOptionPane.showMessageDialog(null,"Debe seleccionar un Producto");
           }else{
               int res=  JOptionPane.showConfirmDialog(null, "Esta seguro de elminiar este producto", "eliminar",JOptionPane.YES_NO_OPTION);
               if(resp==JOptionPane.YES_OPTION){
                   model=(DefaultTableModel) tableProduct.getModel();
                   model.removeRow(btn);
               
           }else{
                   JOptionPane.showMessageDialog(null,"No se puedo eliminar");
                }
           }
           }catch(Exception ex){
           
       }
   
   }
   public void generateBill(File file) {
       String name=txtNameProduct.getText();
      boolean x;
       long Ci=Long.parseLong(txtCI.getText());
       
		        x= Validations.validationId(Ci);
                        if (x==false){
                        JOptionPane.showMessageDialog(null,"cedula incorrecta");
                        }else{
       String telephone=txtNumber.getText(); 
       String location=txtLocate.getText();
		FileManager.saveArrayInFileOfBilling(file, bill, subtotal, iva, totalSold,name,Ci,telephone,location);
		System.out.println("FACTURA GENERADA");
		System.out.println("=>>> Factura <<<==");
		System.out.println((shop.getStoreName()));
		System.out.println("DIA DE FACTURACION: " + java.time.LocalDate.now());
		System.out.println("HORA DE FCATURACION: " + java.time.LocalTime.now());
		System.out.println("VALOR TOTAL A PAGAR : " + totalSold);
	}
   }
     public void generateBillConsumerEnd(File file) {
               
		FileManager.saveArrayInFileOfBillingConsumerEnd(file, bill, subtotal, iva, total);

   }                  


  
     
  
          
  
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Group1;
    private javax.swing.JButton btnAgregation;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGenerateBilling;
    private javax.swing.JComboBox<String> cmbxNameProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblProduct;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCi;
    private javax.swing.JLabel lblLocate;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JRadioButton radiobtnConsumerEnd;
    private javax.swing.JRadioButton radiobtnInformation;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtLocate;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtQuantly;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


 
}

