/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.solfadministration.model.GUI;

import java.awt.Color;

/**
 *
 * @author SAOM
 */
public class FrmAdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdminMenu
     */
    public FrmAdminMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblBackgroundMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAdmin = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        MenuStaff = new javax.swing.JMenu();
        ItemMenuAddEmployee = new javax.swing.JMenuItem();
        ItemRemoveEmployee = new javax.swing.JMenuItem();
        MenuInventory = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuViewEmployee = new javax.swing.JMenu();
        ViewEmployee = new javax.swing.JMenu();
        MenuVerEmpleados = new javax.swing.JMenuItem();
        ViewInventory = new javax.swing.JMenu();
        seeInventory = new javax.swing.JMenuItem();
        viewSales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRADOR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/espe/edu/solfadministration/images/20190113_150008_0001.png"))); // NOI18N

        MenuAdmin.setText("Admin");

        jMenuItem4.setText("Menú");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuAdmin.add(jMenuItem4);

        jMenuBar1.add(MenuAdmin);

        MenuEdit.setText("Editar");

        MenuStaff.setText("Personal Laboral");

        ItemMenuAddEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        ItemMenuAddEmployee.setText("Añadir Empleado");
        ItemMenuAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuAddEmployeeActionPerformed(evt);
            }
        });
        MenuStaff.add(ItemMenuAddEmployee);

        ItemRemoveEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        ItemRemoveEmployee.setText("Remover Empleado");
        ItemRemoveEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemRemoveEmployeeActionPerformed(evt);
            }
        });
        MenuStaff.add(ItemRemoveEmployee);

        MenuEdit.add(MenuStaff);

        MenuInventory.setText("Inventario");
        MenuInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInventoryActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Añadir / Eliminar un producto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuInventory.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Modificar ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuInventory.add(jMenuItem2);

        MenuEdit.add(MenuInventory);

        jMenuBar1.add(MenuEdit);

        MenuViewEmployee.setText("Reporte");

        ViewEmployee.setText("Empleados");

        MenuVerEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuVerEmpleados.setText("Visualizar Reporte");
        MenuVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerEmpleadosActionPerformed(evt);
            }
        });
        ViewEmployee.add(MenuVerEmpleados);

        MenuViewEmployee.add(ViewEmployee);

        ViewInventory.setText("Inventario");

        seeInventory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        seeInventory.setText("Revisar Inventario");
        seeInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeInventoryActionPerformed(evt);
            }
        });
        ViewInventory.add(seeInventory);

        MenuViewEmployee.add(ViewInventory);

        viewSales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        viewSales.setText("Ventas");
        viewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesActionPerformed(evt);
            }
        });
        MenuViewEmployee.add(viewSales);

        jMenuBar1.add(MenuViewEmployee);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblBackgroundMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblBackgroundMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemRemoveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemRemoveEmployeeActionPerformed
        FrmRemoveStaff frmRemoveEmployee = new FrmRemoveStaff();
        frmRemoveEmployee.setLocationRelativeTo(null);
        frmRemoveEmployee.setVisible(true);
        frmRemoveEmployee.getContentPane().setBackground(Color.lightGray);
    }//GEN-LAST:event_ItemRemoveEmployeeActionPerformed

    private void MenuInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInventoryActionPerformed

    }//GEN-LAST:event_MenuInventoryActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmInventoryModify frmModifyInventory = new FrmInventoryModify();
        frmModifyInventory.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmInventory frmInventory = new FrmInventory();
        frmInventory.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    private void MenuVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerEmpleadosActionPerformed
        FrmViewEmployees frmViewReport = new FrmViewEmployees();
        frmViewReport.setLocationRelativeTo(null);
        frmViewReport.setVisible(true);
        frmViewReport.getContentPane().setBackground(Color.lightGray);
        
    }//GEN-LAST:event_MenuVerEmpleadosActionPerformed

    private void seeInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeInventoryActionPerformed
        FrmInventoryStatus frmInventoryStatus = new FrmInventoryStatus();
        frmInventoryStatus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seeInventoryActionPerformed

    private void viewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesActionPerformed

        StatisticsJFrame statistics=new StatisticsJFrame ();
        statistics.setVisible(true);

    }//GEN-LAST:event_viewSalesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       MenuJframe menuJframe = new MenuJframe(); 
        menuJframe.setLocationRelativeTo(null);
        menuJframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void ItemMenuAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuAddEmployeeActionPerformed
        FrmAddEmployee frmAddEmployee = new FrmAddEmployee();
        frmAddEmployee.setLocationRelativeTo(null);
        frmAddEmployee.setVisible(true);
        frmAddEmployee.getContentPane().setBackground(Color.lightGray);
    }//GEN-LAST:event_ItemMenuAddEmployeeActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMenuAddEmployee;
    private javax.swing.JMenuItem ItemRemoveEmployee;
    private javax.swing.JLabel LblBackgroundMenu;
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuInventory;
    private javax.swing.JMenu MenuStaff;
    private javax.swing.JMenuItem MenuVerEmpleados;
    private javax.swing.JMenu MenuViewEmployee;
    private javax.swing.JMenu ViewEmployee;
    private javax.swing.JMenu ViewInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem seeInventory;
    private javax.swing.JMenuItem viewSales;
    // End of variables declaration//GEN-END:variables
}
