/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.solfadministration.model.GUI;

import ec.espe.edu.solfadministration.Files.util.FileManager;
import ec.espe.edu.solfadministration.Files.util.Validations;
import ec.espe.edu.solfadministrationprj.model.Product;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Omar Mejia
 */
public class FrmInventoryStatus extends javax.swing.JFrame {
    File file = new File("Product.txt");
    ArrayList<Product> products = new ArrayList<>();
    
     public void cleanComponents(){
        this.txtCode.setText("");
       }
     
     public void cleanTxtArea(){
         this.txtAreaData.setText("");
     }

    /**
     * Creates new form EmployeeJFrame
     */
    public FrmInventoryStatus() {
        initComponents();
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        FileManager.createArrayOfFile(products, file);
        seeInventory(products);
        products.clear();
        this.setLocationRelativeTo(null);
    }
    
    private void seeInventory(ArrayList<Product> product){
        String matriz[][] = new String[product.size()][4];
                for (int i = 0; i < product.size(); i++) {
                    matriz[i][0] = product.get(i).getCodeProduct();
                    matriz[i][1] = product.get(i).getNameProduct();
                    matriz[i][2] = String.valueOf(product.get(i).getCost());
                    matriz[i][3] = String.valueOf(product.get(i).getStock());
                    }
                tblInventory.setModel(new javax.swing.table.DefaultTableModel( matriz,new String []{"Codigo","Nombre","Costo","Stock"}));
                tblInventory.getColumnModel().getColumn(0).setPreferredWidth(20);
                tblInventory.getColumnModel().getColumn(1).setPreferredWidth(150);
                tblInventory.getColumnModel().getColumn(2).setPreferredWidth(20);
                tblInventory.getColumnModel().getColumn(3).setPreferredWidth(20);
    }

    private void consultInformation(){
         try{
                int p=0;
                String costString;
                String stockString;
                FileManager.createArrayOfFile(products, file);
                p = Validations.numberOfArrayProduct(file, products, txtCode.getText());
                if(p  >=0 ){
                costString = String.valueOf(products.get(p).getCost()) ;
                stockString = String.valueOf(products.get(p).getStock());
                    txtAreaData.setText("Código del producto: "+products.get(p).getCodeProduct()+"\n"+
                            "Nombre del producto: "+products.get(p).getNameProduct()+"\n"+
                            "Costo del producto: "+costString+"\n"+
                            "Stock: "+stockString);
                    products.clear();
                            }else{
                    JOptionPane.showMessageDialog(null, "Lo sentimos. Elcódigo ingresado no se encuentra registrado","Producto no registrado",JOptionPane.WARNING_MESSAGE);        
            products.clear();
            }
        }catch(Exception e){
                System.out.println("Se ha producido un Error");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnConsult = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaData = new javax.swing.JTextArea();
        lblCode = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("INVENTARIO");

        btnConsult.setBackground(new java.awt.Color(51, 51, 51));
        btnConsult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsult.setForeground(new java.awt.Color(255, 255, 255));
        btnConsult.setText("Consultar");
        btnConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultActionPerformed(evt);
            }
        });

        txtAreaData.setBackground(new java.awt.Color(51, 51, 51));
        txtAreaData.setColumns(20);
        txtAreaData.setRows(5);
        txtAreaData.setEnabled(false);
        jScrollPane2.setViewportView(txtAreaData);

        lblCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCode.setText("Código del producto:");

        txtCode.setBackground(new java.awt.Color(51, 51, 51));
        txtCode.setForeground(new java.awt.Color(255, 255, 255));
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodeKeyTyped(evt);
            }
        });

        tblInventory.setBackground(new java.awt.Color(51, 51, 51));
        tblInventory.setForeground(new java.awt.Color(255, 255, 255));
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Costo", "Stock"
            }
        ));
        jScrollPane3.setViewportView(tblInventory);

        btnMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnMenu.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConsult)
                        .addGap(78, 78, 78)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenu))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMenu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCode))
                        .addGap(18, 18, 18)
                        .addComponent(btnConsult)
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultActionPerformed
        consultInformation();
    }//GEN-LAST:event_btnConsultActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed

    }//GEN-LAST:event_txtCodeActionPerformed

    private void txtCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyTyped
        if(txtCode.getText().length()>=4){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Solo se admite el ingreso de 4 dígitos");
        }
        if(txtCode.getText().length()>=0){
            cleanTxtArea();
        }
    }//GEN-LAST:event_txtCodeKeyTyped

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        FrmAdminMenu frmAdminMenu =new FrmAdminMenu();
        frmAdminMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventoryStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventoryStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventoryStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventoryStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventoryStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsult;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCode;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextArea txtAreaData;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
