/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.espe.edu.solfadministration.model.GUI;

import ec.espe.edu.solfadministration.Files.util.Date;
import ec.espe.edu.solfadministration.Files.util.Statistic;
import ec.espe.edu.solfadministration.Files.util.Validations;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pancho
 */
public class StatisticsJFrame extends javax.swing.JFrame {

    Statistic statistic = new Statistic();
    ArrayList<String> querySales = new ArrayList<String>();
    Date actualDate = new Date();

    /**
     * Creates new form StatisticsJFrame
     */
    public StatisticsJFrame() {
        initComponents();
        this.setLocation(100, 100);
        this.setMinimumSize(new Dimension(695, 643));
        WindowManager.AllignCenter(lblTitle, this);
        WindowManager.AllignCenter(scrlReport, this);
        WindowManager.AllignCenter(pnlDate, this);
        WindowManager.AllignCenter(btnDay, this);
        WindowManager.AllignCenter(btnMonth, this);
        WindowManager.AllignCenter(lblTotal, this);

        Vector<String> years = new Vector<>();
        Date actualDate = new Date();
        for (int i = actualDate.getActualYear(); i > 2000; i--) {

            cmbYear.addItem(String.valueOf(i));
        }

        for (int i = 12; i > 0; i--) {

            cmbMonth.addItem(String.valueOf(i));
        }

        for (int i = 31; i > 0; i--) {

            cmbDay.addItem(String.valueOf(i));
        }

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    
    private void seeReport(ArrayList<String> saleData) {

        String matriz[][] = new String[saleData.size()][4];
        for (int i = 0; i < saleData.size(); i++) {
            matriz[i][0] = saleData.get(i).split("-")[0];
            matriz[i][1] = saleData.get(i).split("-")[1];

            String aux = saleData.get(i).split("-")[2];
            matriz[i][2] = aux.split("|")[0] + aux.split("|")[1];

            System.out.println(matriz[i][2]);

            matriz[i][3] = Character.toString(aux.charAt(6)) + Character.toString(aux.charAt(7)) + Character.toString(aux.charAt(8)) + "  ";
            System.out.println(matriz[i][3]);

        }
        DefaultTableModel modelTable = new DefaultTableModel(matriz, new String[]{"Año", "Mes", "Día", "Ventas"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        lblTotal.setText("TOTAL: " + statistic.getValueIncome());
        tblReport.setModel(modelTable);

    }

    ;
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnDay = new javax.swing.JButton();
        btnMonth = new javax.swing.JButton();
        lblErrorDate = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        scrlReport = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        pnlDate = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnQuery = new javax.swing.JButton();
        cmbYear = new javax.swing.JComboBox<>();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbDay = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(139, 0, 0));
        lblTitle.setText("Statistics");

        btnDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDay.setText("Ventas del día");
        btnDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayActionPerformed(evt);
            }
        });

        btnMonth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMonth.setText("Ventas del mes");
        btnMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthActionPerformed(evt);
            }
        });

        lblErrorDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrorDate.setForeground(new java.awt.Color(255, 0, 0));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotal.setText("TOTAL:     ");

        tblReport.setAutoCreateRowSorter(true);
        tblReport.setBackground(new java.awt.Color(51, 51, 51));
        tblReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblReport.setForeground(new java.awt.Color(255, 255, 255));
        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Año", "Mes", "Día", "Ventas"
            }

        )
        {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }

        }

    );
    jScrollPane2.setViewportView(tblReport);

    scrlReport.setViewportView(jScrollPane2);

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel4.setText("Día");

    btnQuery.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    btnQuery.setText("Consultar");
    btnQuery.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnQueryActionPerformed(evt);
        }
    });

    /*
    cmbYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    */
    cmbYear.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmbYearActionPerformed(evt);
        }
    });

    cmbMonth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    cmbDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel2.setText("Año");

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel3.setText("Mes");

    javax.swing.GroupLayout pnlDateLayout = new javax.swing.GroupLayout(pnlDate);
    pnlDate.setLayout(pnlDateLayout);
    pnlDateLayout.setHorizontalGroup(
        pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDateLayout.createSequentialGroup()
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlDateLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel2)))
            .addGap(84, 84, 84)
            .addGroup(pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(pnlDateLayout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGroup(pnlDateLayout.createSequentialGroup()
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(74, 74, 74)
                    .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(80, 80, 80)
            .addComponent(btnQuery))
    );
    pnlDateLayout.setVerticalGroup(
        pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlDateLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
            .addGap(25, 25, 25)
            .addGroup(pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnQuery))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(pnlDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(126, 126, 126)
                    .addComponent(lblErrorDate))
                .addGroup(layout.createSequentialGroup()
                    .addGap(286, 286, 286)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(scrlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(58, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(158, 158, 158)
                    .addComponent(btnDay)
                    .addGap(72, 72, 72)
                    .addComponent(btnMonth))
                .addGroup(layout.createSequentialGroup()
                    .addGap(234, 234, 234)
                    .addComponent(lblTotal)))
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnDay)
                .addComponent(btnMonth))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(lblErrorDate))
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(pnlDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addComponent(scrlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(38, 38, 38)
            .addComponent(lblTotal)
            .addContainerGap(47, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearActionPerformed

    }//GEN-LAST:event_cmbYearActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        int queryYear = Integer.parseInt(String.valueOf(cmbYear.getSelectedItem()));

        int queryDay = Integer.parseInt(String.valueOf(cmbDay.getSelectedItem()));

        int queryMonth = Integer.parseInt(String.valueOf(cmbMonth.getSelectedItem()));

        Date queryDate = new Date(queryYear, queryMonth, queryDay);
        System.out.println(queryDate.getDate());
        queryDate = Validations.ValidateBirthDate(queryDate);
        if (queryDate.getDate().equals("-1/-1/-1")) {
            lblErrorDate.setText("Fecha incorrecta");
        } else {
            lblErrorDate.setText("");
        }

        querySales = statistic.viewStatisticsBySpecificDate(queryYear, queryMonth, queryDay);

        seeReport(querySales);


    }//GEN-LAST:event_btnQueryActionPerformed

    private void btnDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayActionPerformed

        querySales = statistic.viewStatisticsByDay();

        seeReport(querySales);


    }//GEN-LAST:event_btnDayActionPerformed

    private void btnMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthActionPerformed

        querySales = statistic.viewStatisticsByMonth();

        seeReport(querySales);

    }//GEN-LAST:event_btnMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDay;
    private javax.swing.JButton btnMonth;
    private javax.swing.JButton btnQuery;
    private javax.swing.JComboBox<String> cmbDay;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDate;
    private javax.swing.JScrollPane scrlReport;
    javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
